"""Per-video inventory of the PitVis dataset.

Probes every video (duration, resolution, fps, frame count), loads every
annotation CSV, and verifies the data facts recorded in CLAUDE.md:

- annotations are one row per second, contiguous 0..N-1
- ann_rows == ceil(nb_frames / round(fps)) + 1 for every labeled video
- the trailing extra annotation row is background (-1)
- step -1 and instrument -1 coincide exactly

Writes notes/inventory.md.

Usage: python src/inventory.py
"""

import json
import math
import subprocess
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "26531686"
OUT = ROOT / "notes" / "inventory.md"

STEP_IDS = [-1] + list(range(1, 15))


def probe(video: Path) -> dict:
    cmd = [
        "ffprobe", "-v", "error", "-select_streams", "v:0",
        "-count_packets",
        "-show_entries", "stream=width,height,r_frame_rate,nb_read_packets",
        "-show_entries", "format=duration",
        "-of", "json", str(video),
    ]
    info = json.loads(subprocess.run(cmd, capture_output=True, check=True).stdout)
    s = info["streams"][0]
    num, den = s["r_frame_rate"].split("/")
    return {
        "width": int(s["width"]),
        "height": int(s["height"]),
        "fps": int(num) / int(den),
        "nb_frames": int(s["nb_read_packets"]),
        "duration": float(info["format"]["duration"]),
    }


def load_annotations(vid: int) -> pd.DataFrame | None:
    path = DATA / f"annotations_{vid:02d}.csv"
    if not path.exists():
        return None
    df = pd.read_csv(path)
    assert (df["int_video"] == vid).all(), f"video {vid}: int_video mismatch"
    assert (df["int_time"].values == range(len(df))).all(), \
        f"video {vid}: int_time not contiguous 0..N-1"
    bg_step = df["int_step"] == -1
    bg_inst = df["int_instrument1"] == -1
    assert (bg_step == bg_inst).all(), f"video {vid}: step/instrument -1 disagree"
    return df


def main() -> None:
    rows = []
    step_totals = {k: 0 for k in STEP_IDS}
    for vid in range(1, 26):
        video = DATA / f"video_{vid:02d}.mp4"
        p = probe(video)
        ann = load_annotations(vid)
        row = {
            "video": vid,
            "duration_s": p["duration"],
            "res": f'{p["width"]}x{p["height"]}',
            "fps": p["fps"],
            "nb_frames": p["nb_frames"],
            "n_extractable": math.ceil(p["nb_frames"] / round(p["fps"])),
            "ann_rows": None,
            "offby1_ok": None,
            "tail_bg": None,
        }
        if ann is not None:
            row["ann_rows"] = len(ann)
            row["offby1_ok"] = len(ann) == row["n_extractable"] + 1
            row["tail_bg"] = int(ann["int_step"].iloc[-1]) == -1
            for k, n in ann["int_step"].value_counts().items():
                step_totals[int(k)] += int(n)
        rows.append(row)
        print(f'video {vid:02d}: {p["duration"]:7.0f}s {row["res"]} '
              f'{p["fps"]:.3f}fps frames={p["nb_frames"]} '
              f'ann={row["ann_rows"]} offby1_ok={row["offby1_ok"]}')

    inv = pd.DataFrame(rows)
    labeled = inv.dropna(subset=["ann_rows"])
    assert labeled["offby1_ok"].all(), "off-by-one relation violated"
    assert labeled["tail_bg"].all(), "a video does not end in background"

    steps = pd.read_csv(DATA / "map_steps.csv")
    id_col, name_col = steps.columns[0], steps.columns[1]
    step_names = {}
    for _, r in steps.iterrows():
        step_names.setdefault(int(r[id_col]), str(r[name_col]).strip())
    step_names[-1] = "background"

    total = sum(step_totals.values())
    OUT.parent.mkdir(exist_ok=True)
    with open(OUT, "w") as f:
        f.write("# PitVis inventory\n\nGenerated by `src/inventory.py`.\n\n")
        f.write("## Videos\n\n")
        f.write("| video | duration (s) | res | fps | frames | extractable @1fps | ann rows | off-by-1 ok | tail bg |\n")
        f.write("|---|---|---|---|---|---|---|---|---|\n")
        for _, r in inv.iterrows():
            ann_str = "—" if pd.isna(r["ann_rows"]) else f'{int(r["ann_rows"])}'
            f.write(f'| {r["video"]:02d} | {r["duration_s"]:.0f} | {r["res"]} '
                    f'| {r["fps"]:.3f} | {r["nb_frames"]} | {r["n_extractable"]} '
                    f'| {ann_str} | {r["offby1_ok"]} | {r["tail_bg"]} |\n')
        f.write(f"\nLabeled videos: {len(labeled)} / 25 "
                f"({total} annotated seconds total).\n")
        f.write("\n## Step distribution\n\n")
        f.write("| step | name | seconds | % | videos |\n|---|---|---|---|---|\n")
        for k in STEP_IDS:
            n = step_totals[k]
            nvid = sum(
                1 for vid in range(1, 26)
                if (df := load_annotations(vid)) is not None
                and (df["int_step"] == k).any()
            )
            f.write(f'| {k} | {step_names[k]} | {n} | {100 * n / total:.2f} | {nvid} |\n')
    print(f"\nAll checks passed. Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
